#! /usr/bin/env ruby
# frozen_string_literal: true

# (C) Wei Chen (willsmile)
# MIT license

require 'logman'
require 'optparse'

LOGMANPATH = ENV.fetch("LOGMANPATH")
CONFIG_FILENAME = 'config.yml'
NON_OPERATIONAL_OPTS = [:config]

# default value
config_path = LOGMANPATH + '/' + CONFIG_FILENAME
@options = {}

opts = OptionParser.new do |opts|
  opts.on('-c', '--config FILE', 'Use a config file') { |v| @options[:config] = v }
  opts.on('-g', '--generate', 'Generate a log') { |v| @options[:generate] = v }
  opts.on('-o', '--open', 'Open generated log') { |v| @options[:open] = v }
  opts.on('-p', '--plugin [NAMES]', 'Run one or multiple plugins', Array) { |v| @options[:plugin] = v }
  opts.on('-e', '--esa', 'Post a log to esa') { |v| @options[:esa] = v }
  opts.on('-s', '--slack', 'Post a log to slack') { |v| @options[:slack] = v }
  opts.on('-v', '--version', 'Show tool version') { |v| @options[:version] = v }

  opts.parse!(ARGV)
end

config_path = @options[:config] if @options.has_key?(:config)
config = Logman::Config.new(config_path)
log = Logman::LogObject.new(config)
post = Logman::Post.new(config)
plugin_manager = Logman::PluginManager.new(config)

@options.each do |k, v|
  case k
  when :generate
    log.generate
  when :open
    log.open
  when :esa
    post.esa(log)
  when :slack
    post.slack(log)
  when :plugin
    v.each { |c| plugin_manager.execute(c) } unless v.nil?
  when *NON_OPERATIONAL_OPTS
    # Do nothing here
  else
    Logman.version
  end
end
